version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: devops_db
    volumes:
      - ./db_create.sh:/docker-entrypoint-initdb.d/db_create.sh
    ports:
      - "3306:3306"